### PR TITLE
Workaround for opted out CF mods

### LINKED ISSUE #1342: Instance Download Failed, The url argument must be of type string
**Describe the bug**
When installing [this modpack](https://oitsjustjose-sharex.s3.us-east-2.amazonaws.com/2022/05/ForgeServ-6.0.1.zip), I receive the error:

```log
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received null
```

**To Reproduce**
1. Download the modpack export from above, and import it
2. After the Forge install succeeds, wait for the failure popup

**Expected behavior**
The pack update works fine

**Possible solutions**
No ideas honestly, I'm dumbfounded

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Operating System:**
- OS: Windows
- Version: 11
- Java Version: 17
- Minecraft Version: 1.18.2
- Mod Loader: Forge

**Additional context**

GDLauncher Version 1.1.23.

You can also install from CurseForge to receive the same failure -- [this version](https://www.curseforge.com/minecraft/modpacks/forgeserv/files/3794746) of the modpack installed just fine on Tuesday 5/17, and today won't install.

### PR DESCRIPTION
**Pull request by Ladvace**

### CODE REVIEW

**Review by Eskaan — APPROVED** [review]

File: public/electron.js [hunk 1]
```diff
@@ -602,6 +602,89 @@ ipcMain.handle('shutdown-discord-rpc', () => {
...
+
+  mainWindow.on('closed', mainWindowListener);
+
+  for (const mod of mods) {
+    if (!win) return;
+    const { modManifest, addon } = mod;
+    try {
+      // eslint-disable-next-line no-loop-func
+      await new Promise((resolve, reject) => {
+        const modUrlDownloadPage = `https://www.curseforge.com/minecraft/mc-mods/${addon.slug}/download`;
```
Comment (commandhat) [inline public/electron.js]: Is this a lazy attempt to scrape download urls from the /download project page? If so, you're going to have issues about MC versions not being respected, especially if you're trying to, say, download a 1.16 mod that has a 1.18 version.

Comment (SirOMGitsYOU) [reply public/electron.js]: Already ran into this issue, when trying to install one of my own modpacks FancyMenu downloads the latest 1.18 version as appose to the 1.16 version :(

Comment (Ladvace) [reply public/electron.js]: ok need to find a fix for this too

Comment (DioEgizio) [reply public/electron.js]: also this will fail when a modpack has an opted out resourcepack, since the url is different.
Probably it's better to get the websiteurl and adding /download/(fileid) [like polymc does](https://github.com/PolyMC/PolyMC/blob/147bde5294626d7ba1a6cd672200f7da878eddd9/launcher/modplatform/flame/FileResolvingTask.cpp#L117)

Comment (commandhat) [reply public/electron.js]: It looks like the project page `/files/all` lets you scrape download links for any of the files in the project, and there's some sort of `filter-game-version` variable you can use to look for MC versions, although how they're currently filtering MC versions is not immediately obvious to me.
Here's an example link that requests all versions of **Just Enough Items** for **MC 1.17.1 only**: https://www.curseforge.com/minecraft/mc-mods/jei/files/all?filter-game-version=2020709689%3A8516

Comment (Ladvace) [reply public/electron.js]: could you tell me which modpack with opted-out resource packs did you try?

Comment (Ladvace) [reply public/electron.js]: I'm not scaping the page, I'm just opening the URL in an electron page and downloading the file in the right folder

Comment (DioEgizio) [reply public/electron.js]: https://github.com/gorilla-devs/GDLauncher/pull/1345/commits/295e9ac12900faff9618c29fbca53517b95e772d it's simpler than this, get the downloadurl from the API and add /download/(fileid) to it

Comment (commandhat) [reply public/electron.js]: That doesn't work if the mod in question restricts 3rd party launchers, which is *the entire point of this PR.*

Comment (DioEgizio) [reply public/electron.js]: what? You can get websiteurl even if the mod is opted out

Comment (Ladvace) [reply public/electron.js]: you mean the `websiteUrl`

Comment (SirOMGitsYOU) [reply public/electron.js]: So i just tested again with https://github.com/Ladvace/GDLauncher/commit/295e9ac12900faff9618c29fbca53517b95e772d and the mods downloaded were 1:1 for the modpack, 

One thing I did come across which completely froze up the system was if a mod in a modpack gets removed off CF the opt'd out mod list just freezes, maybe adding a check for a 404 not found page or a manual "skip mod" button should it happen, it's probably an extremely rare case scenario, but it just hit me twice with Macaws Bridges addon mods for environmental and buzzier bees as an example.

**Comment by commandhat** [comment]
~~The addition of the cancel button solves my ( and @SirOMGitsYOU ) last complaint. In 100 feet, merge left onto Source Highway. (Assuming the review happens soon, anyway.)~~

**Comment by SirOMGitsYOU** [comment]
> The addition of the cancel button solves my ( and @SirOMGitsYOU ) last complaint. Next stop, merge highway! 🏎️ (assuming the review happens sometimes soon, anyway...)

🥳 will give it another test tonight and feedback!

**Comment by SirOMGitsYOU** [comment]
Update! - Just tested this the addition of the cancel button doesn't seem to resolve the prior issue mentioned as the "Cancel" button is greyed out, but it still poses the issue where the modpack is not installable should there be a mod that no longer exists and 404s, I tested the same modpack on the Official CF launcher and noticed the official launcher has no issues downloading non-existing mods anymore? potentially something only locked for the official launcher due to the API issues,

Instead of a cancel button would a "Skip" button be more applicable here (or both?) to skip the current mod download to proceed with the installation.

**Comment by commandhat** [comment]
> I tested the same modpack on the Official CF launcher and noticed the official launcher has no issues downloading non-existing mods anymore?

Give me the name of a modpack with a no-longer-existant mod and I can see what URL the CF launcher is calling.

**Comment by SirOMGitsYOU** [comment]
> > I tested the same modpack on the Official CF launcher and noticed the official launcher has no issues downloading non-existing mods anymore?
> 
> Give me the name of a modpack with a no-longer-existant mod and I can see what URL the CF launcher is calling.

Use ABOE 3 - the mods that don’t exist anymore are macaws bridges buzzier bees & environmental

**Comment by commandhat** [comment]
I'm still looking, ~~haven't found any results yet,~~ but for those of you wanting to help, here's the manifest entry for one such 'missing mod' that CurseForge's launcher is magically able to retrieve:

`{"projectID":544574,"fileID":3652281,"required":true},`

This mod does not exist on Curse's website or in the API yet CF's downloader is able to pull this specific file.

**Comment by commandhat** [comment]
Update: Looks like CF's own launcher violates their ToS.
Rebuilding the CDN link manually gives a valid URL which can be used to download the above mod, even if the project was deleted:
(link hidden to protect privacy.)

**Comment by SirOMGitsYOU** [comment]
> Update: Looks like CF's own launcher violates their ToS. Rebuilding the CDN link manually gives a valid URL which can be used to download the above mod, even if the project was deleted: 
**_<there was a URL here but it's an illegal curseforge URL>_**

Brilliant lol I guess one rule for everyone else I guess it is their own API lol

**Comment by DioEgizio** [comment]
Remember guys, it's the CurseForge **3rd Party** API Terms and Conditions 🤡

**Comment by DioEgizio** [comment]
It's actually even worse, with CF launcher key it resolves fine

**Comment by commandhat** [comment]
> Brilliant lol I guess one rule for everyone else I guess it is their own API lol

For publicity concerns, could you edit the URL out of this reply?

**Comment by SirOMGitsYOU** [comment]
> > Brilliant lol I guess one rule for everyone else I guess it is their own API lol
> 
> For publicity concerns, could you edit the URL out of this reply?

Done :) 

EDIT: Removed the revision history too so it's not locatable

**Comment by SirOMGitsYOU** [comment]
Latest change to skip 404 mods works however once all downloads finish it just gets stuck with the continue button not working https://i.imgur.com/EUUTc5N.png

EDIT: Neither the cancel or continue buttons work and you can't even exit out the menu as it's locked in

**Comment by SirOMGitsYOU** [comment]
Secondary Update: After further tests, it would look like the issue also plagues over the updating mod scenario where the mods are opted out the updater just gets stuck regardless if you manually update or update all. 

If possible to apply the manual download window maybe for all updates to show you whats being updated and then showing the browser when mods need to be manually downloaded

**Review by SirOMGitsYOU — COMMENTED** [review]
Just tested this, downloading from the "Add mods" and searching for a mod to download i.e in my examples I used "FancyMenu" and "Drippy Loading Screen" on 1.16.5 forge, worked fine the window pops up and it downloads. 

However when trying to update or change versions from the modlist just outright deletes the mod and no update ever takes place, no window pops up - this also if installing a mod and for some reason fails to download i.e the window gets closed or this issue happens it still marks the mod as installed even though it definitely isn't.

Managed to catch this error message which might help track down the issue - 
image

**Comment by SirOMGitsYOU** [comment]
That's fixed the issue regarding it not getting unloaded from the modlist, still however just deletes the mod no browser window pops up to download the update.

**Comment by Ladvace** [comment]
> till however just deletes the mod no browser window

what pack are you trying?

**Comment by SirOMGitsYOU** [comment]
> > till however just deletes the mod no browser window
> 
> what pack are you trying?

So I was just trying individual mods for this not necessarily a pack as I was only on my lunch break from work I was just using it as i normally would for developing packs installing then simulating a  mod update by putting in an older version or using a profile with old mods that are definitely opt'd out and then this happens.

you can do this if you install a profile and install either fancymenu or drippy loading screen both are opt'd out and you can replicate the same thing, can provide a video of the issue if you'd like

**Comment by SirOMGitsYOU** [comment]
Getting this error message now when updating mods through the mods menu - 
image
image


Also not sure if something can be done about this but In  my testing I got this page basically everytime apart from the 1 time I managed to get it to download 
image

It goes to "Please stand by checking browser" etc then it just loops to the start where you have to click the I'm not a robot box then it loops indefinitely until the mod download times out.

**Comment by Ladvace** [comment]
> Getting this error message now when updating mods through the mods menu - image image
> 
> Also not sure if something can be done about this but In my testing I got this page basically everytime apart from the 1 time I managed to get it to download image
> 
> It goes to "Please stand by checking browser" etc then it just loops to the start where you have to click the I'm not a robot box then it loops indefinitely until the mod download times out.

not sure how to test the captcha, I' ve been testing it for a while and I never got it, need to check

**Comment by Ladvace** [comment]
> Getting this error message now when updating mods through the mods menu -

mmm, do you get it with all the mods?

**Comment by SirOMGitsYOU** [comment]
> > Getting this error message now when updating mods through the mods menu -
> 
> mmm, do you get it with all the mods?

Happens with all mods!

**Comment by Ladvace** [comment]
> Happens with all mods!

if you have discord could you dm me there?

**Comment by SirOMGitsYOU** [comment]
> > > Getting this error message now when updating mods through the mods menu -
> >
> > mmm, do you get it with all the mods?
>
> if you have discord could you dm me there?

Yeah I can add you on discord

**Comment by SirOMGitsYOU** [comment]
Just been on and tested these, not sure if you changed how the pages load but I'm never getting a page failing to load searched up multiple keywords and event spammed through them as much as I can and can't trigger the page to fail to load so good work if you fixed it, otherwise it might just be curseforge taking a big slowdown that causes it.


As for mod updates and changing versions absolutely perfection couldn't find any faults with it at all. 

Looks all good from what I can see! 


p.s had a suggestion regarding re-menuing the updating mods screen
(One thing that might be nice but not a necessity or bugfix may be adding the window that is used to install the opted-out mods having that be the window that shows instead of "Updating mods 1/20", it could be a nicer menu to view especially for people who just click update all just a suggestion :P)

**Comment by Ladvace** [comment]
> Just been on and tested these, not sure if you changed how the pages load but I'm never getting a page failing to load searched up multiple keywords and event spammed through them as much as I can and can't trigger the page to fail to load so good work if you fixed it, otherwise it might just be curseforge taking a big slowdown that causes it.

i disabled the switch version button when it's not ready

**Comment by Ladvace** [comment]
> p.s had a suggestion regarding re-menuing the updating mods screen
> (One thing that might be nice but not a necessity or bugfix may be adding the window that is used to install the opted-out mods having that be the window that shows instead of "Updating mods 1/20", it could be a nicer menu to view especially for people who just click update all just a suggestion :P)

I try to add it today, otherwise we merge it and we open a new pr to fix other bugs

**Comment by SirOMGitsYOU** [comment]
> > Just been on and tested these, not sure if you changed how the pages load but I'm never getting a page failing to load searched up multiple keywords and event spammed through them as much as I can and can't trigger the page to fail to load so good work if you fixed it, otherwise it might just be curseforge taking a big slowdown that causes it.
> 
> i disabled the switch version button when it's not ready

Just tried to get the limbo screen again can't get it, that page must only occur when the CF system is running on it's potato mode, but from what you've said aslong as it's preventing download it should be fine, i will keep an eye on it if it is merged and will postback any feedback.

**Comment by SirOMGitsYOU** [comment]
> > p.s had a suggestion regarding re-menuing the updating mods screen
> > (One thing that might be nice but not a necessity or bugfix may be adding the window that is used to install the opted-out mods having that be the window that shows instead of "Updating mods 1/20", it could be a nicer menu to view especially for people who just click update all just a suggestion :P)
> 
> I try to add it today, otherwise we merge it and we open a new pr to fix other bugs

Just tried to update a large pack with 62 mod updates and the moment I hit an opted out mod my browser window gets challenged: 

image

As before it loops indefinitely 

image

**Comment by commandhat** [comment]
The electron update seems to have fixed the challenges! Was able to download 3 modpacks in a row no problems.

**Comment by SirOMGitsYOU** [comment]
For sure just spoke to Ladvace via discord, was easily able to download multiple instances easily 1k mods+ (not all opted out but still a lot) and no issues!

**Comment by Eskaan** [comment]
@Ladvace so this pr is ready?

**Comment by Ladvace** [comment]
> @Ladvace so this pr is ready?

I think Davide wants to wait for another pr be merged first

**Comment by SirOMGitsYOU** [comment]
When trying to download https://www.curseforge.com/minecraft/modpacks/mineshafts-monsters on gdl it gives this error message (opted out modpack) attempted to use other opt'd out packs and not able to reproduce this error with gdl.

won't import from zip or download through the menu.

image

**Comment by blarfoon** [comment]
LGTM 👍
